arrays
Egorles/study pull request #1
Opened 2019-12-10 07:57 UTC by Egorles

2019-12-10 10:17 UTC, artempartos requested changes

2019-12-10 10:17 UTC, artempartos commented on test/exercise/arrays/solution.rb
> +        max_elem = array.max
а напиши свою функцию поиска мксимального

2019-12-10 10:17 UTC, artempartos commented on test/exercise/arrays/solution.rb
> +        return array[0] == query ? 0 : -1 if array.length == 1
Вот этот код очень плох тернарник еще и с условием )
давай перепишем функцию в рекурсиивном стиле

2019-12-10 15:29 UTC, Egorles reviewed
Done

2019-12-11 09:14 UTC, artempartos requested changes

2019-12-11 09:14 UTC, artempartos commented on test/exercise/arrays/solution.rb
> +        while i < array.length
в целом в мире руби никто не пишет итерации через while, есть специальные итераторы each, map, reduce... )
попробуй то же самое но с each

2019-12-11 09:14 UTC, artempartos commented on test/exercise/arrays/solution.rb
> +        if array.length == 1
а ты уверен что этта проврка нужна?
допустим мы прислали  массив 
array = [123]
first = 0
last = array.length - 1 = 0
mid = 0
(first <= last) = (0 <= 0) -> выполнится

2019-12-11 11:27 UTC, Egorles commented on test/exercise/arrays/solution.rb
> +        while i < array.length
реализовал через each 
единственное сравнение с нулем не нравится. А сравнение с nil не работает. Есть какое то короткое решение позволяющее сравнивать не задавая начального значения переменной max?

2019-12-11 11:28 UTC, Egorles commented on test/exercise/arrays/solution.rb
> +        if array.length == 1
Убрал проверку, она лишняя

2019-12-11 12:22 UTC, artempartos requested changes

2019-12-11 12:22 UTC, artempartos commented on test/exercise/arrays/solution.rb
> +        max = 0
вот такие три строчки решения - уже гораздо лучше чем было, 
но момент когда
1) ты что-то объявляешь в начале
2) each
3) меняешь  в итераторе обхявленную в начале переменную

 это классический пример когда нужно использовать reduce

2019-12-11 13:49 UTC, artempartos requested changes

2019-12-11 13:49 UTC, artempartos commented on test/exercise/arrays/solution.rb
> +        array.reduce(0) { |max, num| if num > max then num else max end }
последний шаг - ииспользуй тернарный оператор внутрии блока. Сравни со своим начальным кодом

2019-12-11 13:50 UTC, artempartos commented on test/exercise/arrays/solution.rb
> +        array.reduce(0) { |max, num| if num > max then num else max end }
Кстаати, еслии ты 0 не передашь - тоже будет работать, он возьмет первое значение как аккумулятор

2019-12-11 14:29 UTC, Egorles commented on test/exercise/arrays/solution.rb
> +        array.reduce(0) { |max, num| if num > max then num else max end }
> последний шаг - ииспользуй тернарный оператор внутрии блока. Сравни со своим начальным кодом

Done

2019-12-11 15:41 UTC, artempartos approved these changes

2019-12-11 16:10 UTC, artempartos requested changes

2019-12-11 16:10 UTC, artempartos commented on test/exercise/fp/solution.rb
> +        new_array = array.map { |film["country"]| film["country"] > 1 ? film : nil }
|film["country"]| это очень странная форма записи )

2019-12-11 19:38 UTC, Egorles commented on test/exercise/fp/solution.rb
> +        new_array = array.map { |film["country"]| film["country"] > 1 ? film : nil }
> |film["country"]| это очень странная форма записи )

@artempartos это не должно было попасть в коммит, странно

2019-12-12 13:39 UTC, artempartos commented on test/exercise/fp/solution.rb
> +        new_array = array.map { |film["country"]| film["country"] > 1 ? film : nil }
давай тогда удалим из коммиита это задание и смержим )

2019-12-14 08:08 UTC, merged